module.exports = {
    "BINARY_OPERATION": "AST.BINARY_OPERATION",
    "UNARY_OPERATION": "AST.UNARY_OPERATION",
    "FUNCTION": "AST.FUNCTION",
    "NUMBER": "AST.NUMBER",
    "VARIABLE": "AST.VARIABLE"
};